### ISSUE TITLE
Very slow SSR loading time on firefox

### ISSUE THREAD

**Issue by evan-limpide** [garronej/tss-react#127] opened 2022-10-31 09:58 UTC
## Very slow SSR loading time on firefox

Hello, 
So, I posted the same problem on [StackOverflow](https://stackoverflow.com/questions/74111871/slow-ssr-loading-time-on-firefox-mui-tss-react?noredirect=1#comment131066327_74111871) and @garronej  told me to create an issue so I ctrl+v my message here.

I am trying to migrate my CSR website to an <b>SSR</b> one with [Mui v5](https://mui.com/) and [Tss-React](https://docs.tss-react.dev/) to use the JSS Syntax for style. It was successful until i see that on Firefox the loading time is <b>near 20 seconds</b> to initially load the homepage and a little less for the heaviest subPages.

I tried other browsers such as Chrome or Edge and it worked fine with <b>20x less time</b> to fully load a page.

Im' not using framework such as next, or razzle for SSR just Node with <b>express and react</b> so i don't know where this could come from.

<b>[Update]</b>
I used the key 'css' on both cache and it works a lot better  and still don't know why.
Here how i set the both caches in my project:
<details><summary>Show code</summary>

```js
import createCache from '@emotion/cache';

// prepend: true moves MUI styles to the top of the <head> so they're loaded first.
// It allows developers to easily override MUI styles with other styling solutions, like CSS modules.
export default function createEmotionCache() {
  return createCache({ key: 'css'});
}
``` 
```js
import createCache from '@emotion/cache';

// prepend: true moves MUI styles to the top of the <head> so they're loaded first.
// It allows developers to easily override MUI styles with other styling solutions, like CSS modules.
export default function createMuiCache() {
  return createCache({
    key: 'css', prepend:true
  });
}
``` 
</details>

### App.js

<details><summary>Show code for <b>App.js</b></summary>

```js
import { makeStyles } from "tss-react/mui";
import styles from './styles'
[...]
const useStyles = makeStyles()(styles)

export default function App() {
  const location = useLocation();
  const { classes } = useStyles();

  return (
    <CookiesProvider>
        <div className={classes.responsiveMainContainer} >
          <TopMenu />
          <Routes>
            <Route exact path='/' element={<HomePage />} />

            <Route path='/vous-etes' element={<VousEtes />}>
              <Route path=':type/:supplyChoice' element={<VousEtes />} />
            </Route>

            <Route path='/nos-solutions' element={<Solutions />}>
              <Route path=':type' element={<Solutions />} />
            </Route>

            <Route path='/publications/:article?' element={<Publications />} />
            <Route path='/publications' element={<Publications />} />

          </Routes>
        </div>
       <Footer/>
    </CookiesProvider>
  );
}
```

</details>

<b>Clients.js and Server.js</b> created according to [mui - SSR guide](https://mui.com/material-ui/guides/server-rendering/) and [TSS - SSR](https://docs.tss-react.dev/ssr/other-backends) for the tss part

### client.js

<details><summary>Show code for <b>client.js</b></summary>

```js
[...]
import theme from './styles/theme';
import createMuiCache from './createMuiCache';

const cache = createMuiCache();
const tssCache = createEmotionCache();

function Main() {
  return (
    <CacheProvider value={cache}>
      <TssCacheProvider value={tssCache}>
        <ThemeProvider theme={theme}>
          {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
          <CssBaseline />
          <BrowserRouter>
            <App />
          </BrowserRouter>
        </ThemeProvider>
      <TssCacheProvider>
    </CacheProvider>
  );
}

ReactDOM.hydrateRoot( document.querySelector('#root'), <Main />);
```
</details>

### server.js

<details><summary>Show code for <b>server.js</b></summary>

```js
[...]

import renderFullPageExampleMui from './renderFullPageExampleMui.js'
import createMuiCache from './createMuiCache';
import { getTssDefaultEmotionCache } from "tss-react";
import theme from './styles/theme';

function handleRenderTSS(req, res) {
  const cache = createMuiCache();
  const tssCache = createEmotionCache();
  const emotionServers = [
    cache,
    getTssDefaultEmotionCache({ "doReset": true })
  ].map(createEmotionServer);

  const context = { };

  const html = renderToString(
    <CacheProvider value={cache}>
     <TssCacheProvider value={tssCache}>
        <ThemeProvider theme={theme}>
          <CssBaseline />
          <StaticRouter context={ context } location={ req.url }>
            <App />
          </StaticRouter>
        </ThemeProvider>
     <TssCacheProvider>
    </CacheProvider>,
  );

  const styleTagsAsStr = emotionServers.map(
    ({ extractCriticalToChunks, constructStyleTagsFromChunks }) =>
    constructStyleTagsFromChunks(extractCriticalToChunks(html))
  ).join("");
    
  res.send(
    renderFullPageExampleMui(html, styleTagsAsStr)
  );
}

[...]
```

</details>

**Comment by garronej** [comment] 2022-10-31 12:27
Hi @evan-limpide,  
Could you try closing the dev tools on firefox and see if it's still slow.  
I gote bite by this, my dev tool was simulating very slow 3g...

**Comment by garronej** [comment] 2022-10-31 12:31
PS: Having two caches with the same key is undefined behaviour as far as I am concerned.

**Comment by evan-limpide** [comment] 2022-10-31 13:18
I already closed everything and ran on private mode. 
I guess i will give up the both css key, because no matter what i do even if the loading time is really better, it breaks my style overriding

**Comment by garronej** [comment] 2022-10-31 15:04
Can you try with [v4.4.3-rc.0](https://github.com/garronej/tss-react/releases/tag/v4.4.3-rc.0) to see if it fixes it?

**Comment by evan-limpide** [comment] 2022-11-07 13:24
It works much better thank you for your work !!

**Comment by garronej** [comment] 2022-11-08 15:45
Hi @evan-limpide,  
Thank you for the feedback!  
I need your help to understand what fixed it though 🙏🏻 
I changed multiple things in the version I have relised for you but I'm not sure.  
It would greatly help if you could tell me if [4.4.4](https://github.com/garronej/tss-react/releases/tag/v4.4.4) still work as intended or only [4.4.3-rc.0](https://github.com/garronej/tss-react/releases/tag/v4.4.3-rc.0) fixes your problem?  

Thank you very much.

**Comment by evan-limpide** [comment] 2023-01-16 11:29
Hey @garronej ,
Sorry for the late reply, since the migration to SSR wasn't the priority for us at the moment.

I come to you again to say that technically my problem isn't solved but when i looked more into it, the main problem was the flickering that is present on both Chrome and firefox but firefox took much more time to load the js (I guess).

I personally think the last time was just an update problem since i had a moths older version of tss and din't update it. The loading time of the flickering is equal on chrome and firefox now, but the problem is still here.

<details>
<summary><b>Show video of the problem</b></summary> 
  https://user-images.githubusercontent.com/112856629/212666137-4ab25802-8959-4d47-a50d-69c3571e5ab4.mp4
</details>

So i put back here my server.js to see if something is wrong with it since there's just little changes to it:
<details>
<summary><b>Show server.js</b></summary> 

```js
import express from 'express';
import * as React from 'react';
import path from 'path';

import { renderToString } from "react-dom/server";
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider, StyledEngineProvider } from '@mui/material/styles';
import { CacheProvider } from '@emotion/react';
import createEmotionServer from '@emotion/server/create-instance';

import createTssCache from './createTssCache';
import createMuiCache from './createMuiCache';

import App from './App';
import theme from './styles/theme';

import { StaticRouter } from "react-router-dom/server";
import { TssCacheProvider } from 'tss-react';


function renderFullPageExampleMui(html, css) {
  return `
    <!DOCTYPE html>
    <html lang="en">
      <head>
        <title>My page</title>
        ${css}
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,200,300,400,500,600,700,800,900|Quicksand:100,200,300,400,500,600,700,800,900|Sriracha:100,200,300,400,500,600,700,800,900|Ubuntu:100,200,300,400,500,600,700,800,900" rel="stylesheet" />
      </head>
      <body>
        <div id="root">${html}</div>
        <script async src="/build/bundle.js"></script>
      </body>
    </html>
  `;
}


function handleRenderTSS(req, res) {

  const muiCache = createMuiCache();
  const tssCache = createTssCache();

  const emotionServers = [
    // Every emotion cache used in the app should be provided.
    // Caches for MUI should use "prepend": true.
    // MUI cache should come first.
    // createMuiCache(),
    tssCache,
    muiCache,
  ].map(createEmotionServer);

  const context = { };

  // const html = renderToString(<App />);
  const html = renderToString(
    <CacheProvider value={muiCache}>
      <TssCacheProvider value={tssCache}>
        <StyledEngineProvider injectFirst>
          <ThemeProvider theme={theme}>
            {/* CssBaseline kickstart an elegant, consistent, and simple baseline to build upon. */}
            <CssBaseline />
            <StaticRouter context={ context } location={ req.url }>
              <App />
            </StaticRouter>
          </ThemeProvider>
        </StyledEngineProvider>
      </TssCacheProvider >
    </CacheProvider>,
  );
  console.log(">> html created");

  const styleTagsAsStr = emotionServers.map(
    ({ extractCriticalToChunks, constructStyleTagsFromChunks }) =>
    constructStyleTagsFromChunks(extractCriticalToChunks(html))
  ).join("");
  console.log(">> css created : ", styleTagsAsStr);
    
  res.send(
    renderFullPageExampleMui(html, styleTagsAsStr)
  );
}

const app = express();

function returnStatic(req, res){
  res.sendFile(
    path.join(__dirname+ req.path)
  );
}

app
.use('/', express.static('public'))
.get('/*.(js|bmp|webp|png|jpg|svg|ico|gif)',returnStatic)
.use('/build', express.static(path.join('./build')));

// This is fired every time the server-side receives a request.
// app.use(handleRenderExampleMui);
app.use(handleRenderTSS);

const port = 3000;
app.listen(port, () => {
  // eslint-disable-next-line no-console
  console.log(`Listening on ${port}`);
});


```

</details>


Thank you !

**Comment by evan-limpide** [comment] 2023-01-27 15:38
We investigated a little bit more.
The low sloading problem was from the size of the bundle and a minifaction problem that we fixed.
It seems that the firefox engine is less performant than chrome one that's why it was different between the navigators.
The mui doc is working properly and we had no need of the tss-react one.

Thank you for what you did, and thank you for tss-react !

**Comment by garronej** [comment] 2023-01-27 16:01
Ok this is great news sorry I didn't get time to come back to it.

**Closed** 2023-01-27 16:01 UTC
