### ISSUE TITLE
No styles at all in next SSR with react 18 and next 12.1.6

### ISSUE THREAD

**Issue by bdew** [garronej/tss-react#82] opened 2022-05-06 15:21 UTC
I don't know if it's related to whatever was fixed in #78 but after this update I'm not getting almost any styles (neither MUI default nor useStyles) in SSR.

The only styles coming from SSR are those 2 small snippets 

![image](https://user-images.githubusercontent.com/96327/167161140-52b83d0c-6398-4ed2-affe-6a192d9cf0f1.png)

After hydration it fixes itself and looks correct. Also doesn't seem to happen with react 17.

Example repo: https://github.com/bdew/sqp

**Comment by bdew** [comment] 2022-05-06 15:22
The demo in https://github.com/garronej/tss-react/tree/main/src/test/apps/ssr has the same problem (if i update its dependencies so it runs on react 18)

![image](https://user-images.githubusercontent.com/96327/167163104-7efdd07f-e67f-4951-ac3e-7fd993873b56.png)

**Comment by garronej** [comment] 2022-05-06 22:46
@bdew Thank you very much for pointing this out.  

The silly reason why I considered Next SSR fixed is because [I updated the dependency on the wrong demo project](https://github.com/garronej/tss-react/commit/9e1f78a85177087a906d5e0f46d6882f501be586).  

<img width="466" alt="image" src="https://user-images.githubusercontent.com/6702424/167224818-710138a4-06b3-44bf-8ffd-d5d4bb7241e2.png">

Thanks for digging out the issue on Next's repo!  

[I have notifier @mui that Next SSR is still broken](https://github.com/mui/material-ui/issues/32051#issuecomment-1120057998)  

Since the problem is not directly related to `tss-react` but to Next.js + [Emotion with manual configuration of SSR](https://emotion.sh/docs/ssr#advanced-approach) I will wait for a solution to be found by the main tenant.  

Thanks for the detailed report,  

Best regards,

**Comment by AntonOfTheWoods** [comment] 2022-05-08 00:45
Sorry to butt in on a subject I don't really understand, but is this related to the same problem as mentioned [here](https://github.com/reactwg/react-18/discussions/110)? (and which [jss has probably fixed with this](https://github.com/cssinjs/jss/issues/1614))

**Comment by garronej** [comment] 2022-05-08 18:18
Hi @AntonOfTheWoods, thanks for your input,  
Yes it has to do with [this](https://github.com/reactwg/react-18/discussions/110) but I think it's more specifically [this](https://github.com/reactwg/react-18/discussions/108).  
TSS is a wrapper around `@emotion/react` and `@emotion/react` is the style engine used behind the scene by MUI.  
I don't think I should attempt to fix it specifically for TSS, I should wait to see how emotion/MUI/Next.js decide to go about the issue.  
Currently, MUI provide no working configuration that works with Next.js + React 18.  
See [this issue](https://github.com/mui/material-ui/issues/32051) (it should be reopened Monday).   

As soon as a solution is found you can rest assured that I will update `"tss-react/nextJs"` if nessesary and/or update the doc.

**Comment by AntonOfTheWoods** [comment] 2022-05-09 06:37
Thanks @garronej . Actually I am (was!) just using `StrictMode` with normal React 18 and the latest MUI, not using next or SSR at all. In dev mode with `StrictMode` lots of stuff is broken, without `StrictMode` most stuff seems to work ok. There are a few other things that have changed but that might be just related to migrating to `tss-react` (stuff like `"& svg": ...` working a little differently in certain circumstances but not all...). I am migrating `react-admin` to 4, MUI to 5.6 and React to 18, so lots of stuff has little niggles but that is totally expected.

My understanding is that in dev mode they are running something twice, which means several css-in-jss solutions have issues. Is this a different issue, or the same underlying one?

**Comment by garronej** [comment] 2022-05-09 10:41
@AntonOfTheWoods,  
thanks for reporting.  
I am unaware of any issue outside of SSR in Next.js with React 18.  
I have tested [the test SPA create-react-app](https://github.com/garronej/tss-react/tree/main/src/test/apps/spa) with React 18 and `<StrictMode />` and everything is working as expected.  
If you can come up with a specific reproducible issue, I will happily address it.  Ideally, that would be under the form of a testable repo.

**Comment by AntonOfTheWoods** [comment] 2022-05-11 12:41
Actually @garronej it looks like I may have made a false accusation there. Adding `StrictMode` back after fixing a few other things (like nested selectors) has got things working. That is clearly documented though so I guess I was just getting confused. Thanks for your help on this!

**Comment by garronej** [comment] 2022-05-11 13:06
@AntonOfTheWoods Thank you very much for taking the time to give feedback. Much appreciated!

**Comment by garronej** [comment] 2022-05-20 23:16
Working with Next.js v12.1.7-canary.4 🥳

**Closed by garronej** 2022-05-20 23:16 UTC
