### ISSUE TITLE
[CSS form label issue]

### ISSUE THREAD

**Issue by jano-gazashvili-axon** [garronej/tss-react#103] opened 2022-08-24 10:44 UTC
After updating `tss-react` from v3.7.1 to v4.0.0, the Form labels are changed and lost CSS, they have covered text fields 

```
<FormControl
      fullWidth={props.fullWidth}
      required={props.required}
    >
        <InputLabel
          error={props.error}
          htmlFor={props.htmlFor}
          required={props.required}
        >
          <Typography fontSize={14} fontWeight="400" component="span">
            {props.label}
          </Typography>
        </InputLabel>
        {textField}
</FormControl>
```

**Comment by garronej** [comment] 2022-08-24 10:57
Hi @jano-gazashvili-axon,  
Sorry about the update issue.  
I see nothing related to TSS in the snipet you shared.  
Please provide additional information or event better, a test repo.  

Best

**Comment by jano-gazashvili-axon** [comment] 2022-08-24 11:58
(before update/after update), i showed just @mui/material simple code which is responsible for text field and label, it works correctly before `tss-react` update, nothing to share directly about `tss-react`, only thing what i can say is that what you see on images


![image](https://user-images.githubusercontent.com/90605572/186412015-844fc222-63d8-4348-9f8b-b4d9e645adbc.png)

![image](https://user-images.githubusercontent.com/90605572/186411952-5fe85ffe-8bba-4ce3-8b9b-5fbe1f02723f.png)

**Comment by jano-gazashvili-axon** [comment] 2022-08-25 10:33
> I don't question that there is a bug but it can't be narrowed down to the code you shared, TSS is simply not involved here. Maybe you have a container that uses selectors that affects the component in question. Maybe it's the update of MUI that is at fault. Maybe the use of TSS global style...?

if i will update `TSS` version then input behavior is not relevant, when i roll back version input starts working correctly. i am talking when all packages up-to date expected `tss-react`

**Comment by garronej** [comment] 2022-08-25 15:33
@jano-gazashvili-axon I am verry willing to makes whatever it takes to solve your issue but you have to help me help you.  
In the snipet of code you shared TSS is simply not involved.  
What technology are you using? Next.js, Create React App?    
The best would be for you to create a minimal repo that repoduce the issue or to give me access to your codebase.  

If you can't do either of these, try giving me as much context and code snipet as possible so I can figure out what's wrong.

**Comment by jiby-aurum** [comment] 2022-09-02 12:19
@garronej I noticed styles being lost once I updated to v4 as well, but only when I remove providing the cache, which is mentioned as not required here https://docs.tss-react.dev/update-to-v4#removing-noise.

So seemingly not providing the cache, still won't work okay with v4. I will try to figure out what is the actual code that affects when I have time, but for now I put back the cache stuff.

**Comment by jiby-aurum** [comment] 2022-09-02 12:24
@garronej well, as far as I found, its styling unrelated to tss, so seemingly mui still needs the `CacheProvider` to style correctly

**Comment by garronej** [comment] 2022-09-02 12:24
@jiby-aurum,  
Thank you for the feedback!  
Do you confirm upgrading `@mui/material` to a version newer than `5.9.3`?  
Are you in a Next.js setup?  

Anyway if you could tell me what are the problematic components....

**Comment by garronej** [comment] 2022-09-02 12:27
> @garronej well, as far as I found, its styling unrelated to tss, so seemingly mui still needs the CacheProvider to style correctly  

Oh noo,  
If it's the case it mean that I need to dig into MUI's codebase once more.  
Are tou using the latest version of `@emotion/react` and `@emotion/styled` ?  

What options do you provide when creating the cache?

**Comment by jiby-aurum** [comment] 2022-09-02 12:30
@garronej yes, I already had `5.10.3`, and no its not Nest.js setup, plain react project with mui and tss-react.

Component was InputAdornment, code below
```tsx
<InputAdornment position="start" style={{ color: 'black' }}>
      <Icons.Search40 />
</InputAdornment>
```

it was not applying the style. See below the css `.css-9kt8nu-Search-input` seemingly was not added as style without the cache
<img width="1627" alt="Screenshot 2022-09-02 at 2 21 37 PM" src="https://user-images.githubusercontent.com/98774951/188143116-015fda03-67d9-427a-a9e6-d85f0b9fb586.png">
![Uploading Screenshot 2022-09-02 at 2.29.29 PM.png…]()

**Comment by jiby-aurum** [comment] 2022-09-02 12:34
@garronej yes I'm on `11.10.4` for `@emotion/react` and `@emotion/styled`

its plain, just like it is in the documentation
<img width="545" alt="Screenshot 2022-09-02 at 2 34 20 PM" src="https://user-images.githubusercontent.com/98774951/188143928-81538dc6-007c-4a91-b6b2-71c04ca1c834.png">

**Comment by garronej** [comment] 2022-09-02 12:37
Thank you for the detailed report,  
Can you tell me if it works correctly when you set `prepend` to `false`?

**Comment by jiby-aurum** [comment] 2022-09-02 12:43
@garronej nope, does not work if `prepend` is false

**Comment by garronej** [comment] 2022-09-02 13:03
@jiby-aurum,  
Yes yes, I figurred out but still. It should't matter.  
Here, in the last screen shot you have two cache coexisting in your app (`mui` and `css`). This isn't normal.  
When you explicidely provide a cache MUI is supposed to pick it up. Are you sure, in your project you and MUI are using the same instance of `@emotion/react` it wouldn't suprise me if you had both:  
`node_modules/@mui/material/node_modules/@emotion/react` and `node_modules/@emotion/react`  
Is it the case?  

And when you provide no cache could you give me the same screen shot where I can see everything?

**Comment by jiby-aurum** [comment] 2022-09-03 15:13
@garronej I think multiple versions of `@emotion/react` problem is there in my project, as recently I started to see this console warning `You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.`

However, I checked my node_modules and `@emotion/react` is only at the top level, and only version `11.10.4`

Find the styles without providing the cache, in this case, it seems to be just the css cache.
<img width="1628" alt="Screenshot 2022-09-03 at 5 12 18 PM" src="https://user-images.githubusercontent.com/98774951/188276851-248bb9d8-9b1f-4e2e-9722-66f0b1b72e51.png">

**Comment by garronej** [comment] 2022-09-03 16:19
Is Storybook involved?

**Comment by jiby-aurum** [comment] 2022-09-03 18:39
@garronej nope, btw, I was quickly checking where the two calls for `@emotion/react` comes from, and one is from mui, and the second from tss-react

**Comment by jiby-aurum** [comment] 2022-09-03 18:49
@garronej I will rollback my updates to investigate a bit where I started to get the duplicate multiple emotion running warning, because with mui 5.8.0 and css 3.6.2, it was not there

**Comment by jiby-aurum** [comment] 2022-09-03 18:59
@garronej its really weird, I started to get the warning `You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.` just after upgrading `@emotion/react` from `11.9.0` to `11.10.4`, no other changes at all

**Comment by jiby-aurum** [comment] 2022-09-03 19:18
@garronej I have identified the issue, and it's the build system I am using which is vite. Seemingly with vite, in dev run, `mui` loads the cjs version of `@emotion/react` and `css-react` the es version, which means its two different instances of `@emotion/react`, which leads to the problem.

**Comment by jiby-aurum** [comment] 2022-09-03 19:23
@garronej which means the solution for this should be very simple as well, to ship the es version as well. I see that currently `tss-react` is only shipps as cjs. It would be just a build step as the project is anyways es

**Comment by jiby-aurum** [comment] 2022-09-03 19:56
@garronej I did quickly try it out and it fixes the problem for me, I opened a quick PR. Would appreciate if you can push a new version soon.

**Comment by garronej** [comment] 2022-09-09 10:54
@jano-gazashvili-axon This shoud be fixed now with the latest release.   
Please feel free to reopen if it isn't the case.  

Thanks for reporting,  

Best regards,

**Comment by ivan-romanchuk-axon** [comment] 2022-09-15 15:56
@garronej persists with version 4.1.3 

With version 3.7.1 labels are OK, like on first screenshot of [this comment](#issuecomment-1225622504)

With version 4.1.3 labels are broken, same as on second screenshot of mentioned comment

**Comment by garronej** [comment] 2022-09-15 16:02
Hi @ivan-romanchuk-axon,   
Thanks for reporting.  
Can you provide a minimal repo where I could reproduce the bug?

**Comment by ivan-romanchuk-axon** [comment] 2022-09-15 16:35
@garronej [Sandbox](https://codesandbox.io/s/vigilant-gagarin-qwji6y)

It is strange, because in Sandbox for 3.7.1 label is broken too

**Comment by ivan-romanchuk-axon** [comment] 2022-09-15 17:15
@garronej updated sandbox to reproduce an issue. Wrapped `TextField` with `StyledEngineProvider`. With version 3.7.1 label is OK, with version 4.1.3 => broken

**Comment by garronej** [comment] 2022-09-19 16:20
@ivan-romanchuk-axon Sorry I didn't find the time to get to it yet but I will.

**Comment by garronej** [comment] 2022-09-23 00:17
@ivan-romanchuk-axon Ok I see, it's a bug on the MUI side.  
I'll make a PR but in the meantime here is a workaround:  

```diff
    <InputLabel
-       classes={{ root: classes.label, error: classes.error }}
+      classes={{ error: classes.error }}
+       className={classes.label}
    >
```

**Comment by garronej** [comment] 2022-09-24 02:33
Hi @ivan-romanchuk-axon,  
I have submited [a pull request](https://github.com/mui/material-ui/pull/34451) on MUI.

**Comment by garronej** [comment] 2022-09-27 02:34
Hi @ivan-romanchuk-axon and @jano-gazashvili-axon this should be fixed in @mui/material 5.10.7.  
Can you confirm?  
Reopen if it's not the case!  

Best regards,

**Closed by garronej** 2022-09-27 02:34 UTC

**Comment by ivan-romanchuk-axon** [comment] 2022-09-27 06:16
Hello @garronej!

Thanks for your feedback and commitment to this issues. 

Sorry, I was moving out and that's why — busy. I will try to check ASAP, at least in codesandbox.

**Comment by garronej** [comment] 2022-09-27 09:18
@ivan-romanchuk-axon No problem, you are wellcome, thank you for helping me figuring out what was wrong.  

I checked in the sandbox. It does work :)

Best,

**Comment by ivan-romanchuk-axon** [comment] 2022-10-04 13:27
> Hi @ivan-romanchuk-axon, I have submited [a pull request](https://github.com/mui/material-ui/pull/34451) on MUI.

Hello @garronej!

I can confirm that labels are fixed. But it seems that in your PR for MUI `Select` component is missed. After all updates, styles for `Select` are broken.

**Comment by garronej** [comment] 2022-10-04 13:52
Hey @ivan-romanchuk-axon,  
Thanks for reporting again.  

> But it seems that in your PR for MUI Select component was missed.  

Is that so ?  Damn it!  
I didn't directly touch the `<Select />` but maybe one of the connex component where afected.  

![image](https://user-images.githubusercontent.com/6702424/193837473-67eca3e9-093a-4aaa-8630-d8327c920938.png)  

Woul you prepare me a Sandbox or better yet a demo repo where I can reproduce?  

Best regards.

**Comment by ivan-romanchuk-axon** [comment] 2022-10-07 09:45
Hello @garronej!

I updated a [sandbox](https://codesandbox.io/s/vigilant-gagarin-qwji6y?file=/src/App.tsx) for reproducing issue with Select components. Now I chose `tss-react` version 3.7.1, you can see all styles apply well. Then change a version to an actual one, and you will see that styles are broken

**Comment by garronej** [comment] 2022-10-07 09:47
Thank toi for taking the time to produce a reproduction path.

**Comment by garronej** [comment] 2022-10-08 13:14
Hi @ivan-romanchuk-axon,  
I issued a new PR on MUI for adressing the `<Select />` issue.  

https://github.com/mui/material-ui/pull/34659   

Best regards,
