### ISSUE TITLE
Import module error with Vite JS

### ISSUE THREAD

**Issue by fatb38** [garronej/tss-react#164] opened 2023-04-11 12:17 UTC
Hi there ! I'm using TSS React (v4.8.2) in a React project with MUI latest version.
I'm migrating from webpack to Vite JS but getting an error with the library import `Cannot use import statement outside a module`

I have this import `import { GlobalStyles, TssCacheProvider } from 'tss-react'` in the app main file and Vite server failed to launch.

Any idea ? Thanks !
<img width="837" alt="Capture d’écran 2023-04-11 à 14 15 11" src="https://user-images.githubusercontent.com/52196301/231159867-e9898bd3-0aa9-49f7-a02f-5a83641226b3.png">

**Comment by garronej** [comment] 2023-04-11 14:21
I can't reproduce...  
I'm not saying your error isn't legitimate but there must be something specific to your configuration.   
It's not that surprizing, if there were an obvious problem with Vite, I would have known by now...  

Maybe before anything try `rm -rf node_modules yarn.lock && yarn`

**Comment by fatb38** [comment] 2023-04-12 09:33
Hi @garronej,

Thanks for your quick response ;)
I tried to remove all node_modules and package-lock.json and reinstall them but without result, still the same error.
Maybe it's specific, we have a monorepo with many dependencies and some very old pieces of code that need to be updated. 

If you ever want to take a look, you can check [this PR](https://github.com/mdblp/blip/pull/1148), our project is open source. It's composed of several packages, the one which uses TSS-React is Yourloops, it's the main package using the others. 

Anyway thanks for your time 😉

**Comment by garronej** [comment] 2023-04-15 02:15
Hi @fatb38,  

I'm very willing to help if you provide a straight forward reproduction path, with just the PR you linked I don't know how to reproduce the issue.  

Closing but feel free to reopen

**Comment by fatb38** [comment] 2023-04-17 09:36
Hi @garronej,

Glad to see you want to help !! Sorry I didn't give you any explanations.
So to try it you can pull the code on `welcome-to-vitejs` branch.
Then, in the root directory, just do `npm install`, then `npm run build-dependencies` (it will build other needed packages) and finally run the app with `npm run start-dev -w yourloops`
The vite server will launch and try to open the page http://localhost:3001/, and then the error should occured in the vite server

**Comment by garronej** [comment] 2023-05-17 22:58
Ok, I can reproduce, I'm on it 👍🏻

**Comment by garronej** [comment] 2023-05-19 00:30
@fatb38, I have the solution, I'll release a version that works in your setup in the following days.

**Comment by garronej** [comment] 2023-05-19 03:06
@fatb38   It's finaly done. You can now use tss-react in your setup.  
Thanks for reporting!

**Closed by garronej** 2023-05-19 03:06 UTC

**Comment by fatb38** [comment] 2023-05-23 15:40
Hi @garronej 
Just saw you response (I was off for few days).
Thank you very much it's also ok on my side !! 
I can go further, many thanks 😁🎉
