### ISSUE TITLE
Can't navigate to class definition

### ISSUE THREAD

**Issue by ajnozari** [garronej/tss-react#118] opened 2022-09-28 01:22 UTC
I have a weird bug where my classes are auto-filled. My IDE does not seem to determine where the class is initially defined.  

This occurs only when returning a callback, not when an object is passed to makeStyles().  I am using this with MUI and upgraded from v4->v5, so I may have just missed something.

Please let me know if you need any further information and I will do my best to get it to you.

**Comment by garronej** [comment] 2022-09-28 01:23
Hi @ajnozari,   

Can you send me a screenshot?

**Comment by ajnozari** [comment] 2022-09-28 21:55
<img width="560" alt="Screen Shot 2022-09-28 at 5 54 57 PM" src="https://user-images.githubusercontent.com/1380829/192895766-7bdc7b76-dad0-4be4-aee9-19ea5a7cb1d0.png">

That's a screen cap that shows my makestyles and an element using a style, I can include a screencap for the whole page if you want.

**Comment by garronej** [comment] 2022-09-28 22:10
I don't see the relevent things in your screen.  
The important part are cropped.  

What I can already tell you is:  
- A hook should always start with `use` I'm surprised you don't get warnings about it.   
- You don't need to annotate `Theme`

```diff
- const styles = makeStyles()((theme: Theme)=> ({
+ const useStyles = makeStyles()(theme => ({
```

**Comment by ajnozari** [comment] 2022-09-28 22:50
Roger I'll try that and see what happens

**Comment by ajnozari** [comment] 2022-09-28 22:55
<img width="564" alt="Screen Shot 2022-09-28 at 6 55 10 PM" src="https://user-images.githubusercontent.com/1380829/192902697-42ed450d-da82-47c1-9868-e8e9c4d0f621.png">

Here's a smaller screen than the last one easier to see everything

**Comment by garronej** [comment] 2022-09-28 23:14
If I type the exacte same code in VSCode it works:  

<img width="651" alt="image" src="https://user-images.githubusercontent.com/6702424/192904578-f1a99794-2c14-4bbf-8693-3617aa0d31b1.png">

Looks like you are using Inteliji and it's missconfigured....

**Comment by ajnozari** [comment] 2022-09-30 01:10
That's the weird thing, if I don't pass a theme (when not needed), it works fine, and it's able to find the declaration.

It only shows like this when I use an arrow function to pass the theme.

**Comment by ajnozari** [comment] 2022-09-30 09:33
I don’t use VSCode so that won’t help me.

mill try updating typescript and see if that helps.

**Comment by garronej** [comment] 2022-09-30 10:15
> I don’t use VSCode so that won’t help me.  

That will help you make sure that the problem is related to Intelliji....

**Comment by osa911** [comment] 2022-10-03 19:48
I have the same issue
Mainly I use `WebStorm`, but I also checked it in VS Code, and there is the same issue
Also, you can check it at your documentation: https://stackblitz.com/edit/tss-react-wv2set?file=Hello.tsx,index.tsx,tss.ts
Try to open `Hello.tsx` and find definition of `label` className

So IDE shows me the `className` which I define at `makeStyles`
<img width="639" alt="image" src="https://user-images.githubusercontent.com/14163474/193664889-41532843-d24e-42bc-b21e-e92aa1ee22ae.png">

But then if I click on the class definition it could not find the right path. 
<img width="299" alt="image" src="https://user-images.githubusercontent.com/14163474/193664989-e1bcf798-1e9b-4dcf-920d-aded10f0546b.png">

I remember I've played with examples of tss v3 via `WebStorm` and it works fine, but in my project, it did not :(

**Comment by garronej** [comment] 2022-10-03 20:29
@osa911 Thanks for reporting but I think the problem @ajnozari  is facing is different.  
In his case, when he types `classes.` he dosen't get any suggestion.  

Now about the fact that it isn't possible to navigate to the de declaration... this dosen't suprise me, it would be neat if it worked but, to my knoelage, it never did.  

If you can provide evidence of navigation working with older version of TSS I can investigate.

**Comment by osa911** [comment] 2022-10-03 21:44
@garronej I have a fork of your project and there it works)))
https://github.com/osa911/tss-react/blob/main/src/test/apps/ssr/pages/index.tsx

https://user-images.githubusercontent.com/14163474/193691414-db26ab27-035e-43bf-bf1b-d5170f67bc38.mov

**Comment by garronej** [comment] 2022-10-03 22:35
very intresting thank you, I'll see if I can make it work again  
it's true that it's very conveignent

**Comment by osa911** [comment] 2022-10-03 22:37
I've played a little bit locally with this and it looks like a bug, not a feature))

**Comment by garronej** [comment] 2022-10-03 22:50
> I've played a little bit locally with this and it looks like a bug, not a feature))  

lol, I don't understand, what do you mean?

**Comment by osa911** [comment] 2022-10-03 23:00
If I replace import makeStyles
```javascript
import { makeStyles } from "../shared/makeStyles";
``` 
to makeStyles definition 
```javascript
import { createMakeAndWithStyles } from "tss-react";
import { useTheme } from "@mui/material/styles";

export const { makeStyles, useStyles, withStyles } = createMakeAndWithStyles({ useTheme });
```
it will break goto definition...

https://user-images.githubusercontent.com/14163474/193700627-4a3e8848-bcee-47c4-b80d-5015c4a8d2e4.mov

**Comment by ajnozari** [comment] 2022-10-09 04:12
> @osa911 Thanks for reporting but I think the problem @ajnozari is facing is different. In his case, when he types `classes.` he dosen't get any suggestion.
> 
> Now about the fact that it isn't possible to navigate to the de declaration... this dosen't suprise me, it would be neat if it worked but, to my knoelage, it never did.
> 
> If you can provide evidence of navigation working with older version of TSS I can investigate.


> possible

So I'm sorry if I confused you, I do get suggestions, it that when I hover over the `classes.className` my IDE doesn't know where it's being referenced from, weirdly it DOES offer the classes as a suggestion.

Something weird must be going on with PHPStorm for it to not know where the object is defined, but still be able to give it in autocomplete

**Comment by ajnozari** [comment] 2022-10-09 04:13
> I have the same issue Mainly I use `WebStorm`, but I also checked it in VS Code, and there is the same issue Also, you can check it at your documentation: https://stackblitz.com/edit/tss-react-wv2set?file=Hello.tsx,index.tsx,tss.ts Try to open `Hello.tsx` and find definition of `label` className
> 
> So IDE shows me the `className` which I define at `makeStyles` <img alt="image" width="639" src="https://user-images.githubusercontent.com/14163474/193664889-41532843-d24e-42bc-b21e-e92aa1ee22ae.png">
> 
> But then if I click on the class definition it could not find the right path. <img alt="image" width="299" src="https://user-images.githubusercontent.com/14163474/193664989-e1bcf798-1e9b-4dcf-920d-aded10f0546b.png"> I've upgraded `typescript` to `4.8.4`
> 
> I remember I've played with examples of tss v3 via `WebStorm` and it works fine, but in my project, it did not :(

This is the exact issue I'm facing, I just explained it very poorly

**Comment by garronej** [comment] 2022-10-09 04:21
> This is the exact issue I'm facing, I just explained it very poorly   

ok thank you for clearing this out, I didn't read what you said carefully enough.

**Comment by garronej** [comment] 2022-10-11 02:38
Now that I know it is possible to navigate 

> 

Hi @osa911,  @ajnozari  
I tried all I could to reproduce a scenario where this was working but I failed.  😞  

The steps I took  

```bash
git clone https://github.com/garronej/tss-react
cd tss-react
# Back to commit n°500
git checkout 11b4c5884ead610f9f31249b21518647ea69008d
yarn 
yarn build
yarn start_ssr
# > Select TypeScript version > Use Workspace version 4.6.4
```

Then I navigate to `src/test/apps/ssr/pages/index.tsx` and after right click -> Go to definition:  

![image](https://user-images.githubusercontent.com/6702424/194983222-39db4f66-754e-4f0b-8d02-6ed2731d906d.png)

I am very willing to work on this, if this is actually possible with open source tooling.  

I'm afraid that it was only working in the first place for both of you thanks to some Inteliji specific heuristic.  
I'm afraid the TypeScript compiler itself isn't capable of producing the line number where the classes are declared.

**Comment by ajnozari** [comment] 2022-10-22 21:28
Something strange I noticed is that if I pass an object to makeStyles instead of a callback it works fine and I am able to navigate to the definition of the class just fine.

So I agree something weird is happening with TS.

**Comment by garronej** [comment] 2022-10-22 21:54
I'm now convinced of that:  

> I'm afraid that it was only working in the first place for both of you thanks to some Inteliji specific heuristic.
> I'm afraid the TypeScript compiler itself isn't capable of producing the line number where the classes are declared.  

Closing since it's an intellij feature that I have no contrôle about.  

Thanks for reporting anyway.

**Closed** 2022-10-22 21:54 UTC
Labels: help wanted, hacktoberfest-accepted

**Comment by MasterRedStorm** [comment] 2024-06-06 10:49
Has anyone found a way to make the navigation work?
A click on "card" here still moves me to a wrong area.
it worked fine with mui jsx styles.

![grafik](https://github.com/garronej/tss-react/assets/23191670/29bc1691-f8d4-4e65-9d85-58674749b91e)
![grafik](https://github.com/garronej/tss-react/assets/23191670/7d329b90-e083-4506-8bc2-3f536a2c479b)
