### ISSUE TITLE
classes are not applied in correct order

### ISSUE THREAD

**Issue by R-154** [garronej/tss-react#51] opened 2022-01-06 11:26 UTC
Hi,

I'm migrating a project from using jss towards tss-react.
We use MUI5 and after migrating to tss-react i see some classes are changed in order.

I already checked some other topics on this behavior.
What i already did:
- update emotion libs to the latest versions
- added the CacheProvider as a wrapper around MuiThemeProvider
- updated my makeStyles.ts to use tss-react > createMakeStyles
- adding the '&&' rules to the css works, but doesn't sound like a correct solution to me

**As an example:**
On a mui typography the -root styling of mui is applied in a higher order then the classname which we provides to item.
This results in not applying our classname styling to it.

![image](https://user-images.githubusercontent.com/97228433/148375837-dc79c696-b061-4572-a9a3-5f4e066fc02c.png)

**Comment by garronej** [comment] 2022-01-06 13:11
Hi @R-154,  

There is something wrong with your configuration, maybe it's something stupid like you haven't saved or something.  
Like it's documented in the [jss-to-tss migration guide](https://mui.com/guides/migration-v4/#2-use-tss-react) and [here](https://github.com/garronej/tss-react#mui-integration), mui and tss can't use the same emotion cache.  You have to use the `<CacheProvider />`.  

I see it's not the case in your configuration since on your screenshoot both classes have the `tss` prefix.  

If you submit the code source or a sandbox I can point to you what's wrong.

**Comment by R-154** [comment] 2022-01-06 13:34
Thx @garronej for your feedback.
Indeed all classes have the .tss preffix which is not ok i see.

I already added the createCache to the themeProvider. See the code below:

```import React from 'react';
import type { Theme } from '@mui/material/styles';
import { ThemeProvider as MuiThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import './styles.css';
import createCache from '@emotion/cache';
import { CacheProvider } from '@emotion/react';

export const muiCache = createCache({
  key: 'mui',
  prepend: true,
});

const ThemeProvider: React.FC<{ theme: Theme }> = ({ children, theme }) => {
  return (
    <CacheProvider value={muiCache}>
      <MuiThemeProvider theme={theme}>
        <CssBaseline />
        {children}
      </MuiThemeProvider>
    </CacheProvider>
  );
};

export default ThemeProvider;

**Comment by garronej** [comment] 2022-01-06 14:12
I can't puzzle how mui manages tout pick up the tss cache...
Your provider looks fine...
Are you sure you don't have missmatchning version on "@emotion/*"?  
If you can link me the repo or set a playground up for me I will tell you what's wrong.

**Comment by R-154** [comment] 2022-01-06 14:31
I have these versions installed:
- "tss-react": "^3.2.4",
- "@emotion/cache": "^11.7.1"
- "@emotion/react": "^11.7.1",
- "@emotion/styled": "^11.6.0",

**Comment by garronej** [comment] 2022-01-06 14:53
Please run:  

`npm ls @emotion/cache` and `npm ls tss-react`

![image](https://user-images.githubusercontent.com/6702424/148401828-d9de11e6-83bb-4c5f-8fcd-66965e8517d4.png)

**Comment by R-154** [comment] 2022-01-06 15:05
cache:
![image](https://user-images.githubusercontent.com/97228433/148403559-741f5422-0eaa-4638-8324-2e2dbff4ced2.png)

tss-react:
![image](https://user-images.githubusercontent.com/97228433/148403614-7d524ebe-24ee-41a4-817d-ca243606b5f9.png)

**Comment by garronej** [comment] 2022-01-06 15:11
Update emotion core, reinstall everything and do that again

**Comment by garronej** [comment] 2022-01-06 15:13
Are you problems happening in storybook?

**Comment by R-154** [comment] 2022-01-06 15:14
Not only in storybook. Also in the application.

**Comment by garronej** [comment] 2022-01-06 15:14
If yes see this warning:  
![image](https://user-images.githubusercontent.com/6702424/148404946-612eb649-48a6-4301-9c3d-540814dfd47e.png)

**Comment by garronej** [comment] 2022-01-06 15:20
> Not only in storybook. Also in the application.  

Ok then, everything should work.  
Link me your repo or reproduce in a playgroud like codeSandbox or stackblitz.

**Comment by garronej** [comment] 2022-01-06 19:33
Now that I think of it, it's `@emotion/react` that should be confirmed deduped.  

Please run:

![image](https://user-images.githubusercontent.com/6702424/148440503-d44e904c-f454-4f4b-923d-5fc8c296d5f7.png)

**Comment by R-154** [comment] 2022-01-07 06:52
I think thats ok:
![image](https://user-images.githubusercontent.com/97228433/148503828-6353b645-2223-45c6-b91f-b1e16d7bcd49.png)

I now added cx instead of cn (from classnames) to my typography component (which uses MUI).
Now styling is applied correct.

Does this look ok to you? Or should there also be a .mui css prefix visible?
![image](https://user-images.githubusercontent.com/97228433/148503955-65827bed-5e68-4751-90a5-f054359edcb5.png)

**Comment by garronej** [comment] 2022-01-07 09:26
> I now added cx instead of cn (from classnames) to my typography component (which uses MUI).
Now most (not all) of the styling is applied correct.

Yes, that's it. `cx` is not just a utility like `cn` is, it is reordering/merging styles in the header based on the order it receives classes.  

> Should I see different prefixes?

I don't know! You make me play guessing game by not showing me any of your code. I could have told you right away that `cn` was the problem if you had shown me what you wrote. 

Closing now, I won't reopen unless you provide me with a repo or a playground. I am here for you but please respect my time.

**Closed by garronej** 2022-01-07 09:26 UTC
