### ISSUE TITLE
[feature] Auto-generate label property in makeStyles

### ISSUE THREAD

**Issue by olee** [garronej/tss-react#26] opened 2021-10-12 12:52 UTC
To make class names more readable for development like they are in material-ui, I would like to propose the following adjustment to make styles, to make it more compatible with old material-ui v4 makeStyles:

```js
const useStyles = makeStyles({ name: 'MyComponent' })(theme => ({
    root: {
        color: 'red',
    },
    child: {
        color: 'blue',
    },
}));
```

which would internally expand the styles object to the equivalent to

```js
const useStyles = makeStyles()(theme => ({
    root: {
        label: 'MyComponent-root',
        color: 'red',
    },
    child: {
        label: 'MyComponent-child',
        color: 'blue',
    },
}));
```

which would result in the following class names:

```css
.tss-react-s0z026-MyComponent-root { color:red; }
.tss-react-pc49kh-MyComponent-child { color:blue; }
```

The following adjusted version of makeStyles would be able to perform this logic (which is what I am currently using and everyone else can easily patch into their own app as well:

```ts
const { useStyles } = createMakeStyles({ useTheme });

export default function makeStyles<Params = void>(opt?: { name?: string; }) {
    const labelPrefix = opt?.name ? `${opt.name}-` : '';
    return function <RuleName extends string>(
        cssObjectByRuleNameOrGetCssObjectByRuleName: Record<RuleName, CSSObject> | ((theme: Theme, params: Params, createRef: () => string) => Record<RuleName, CSSObject>)
    ) {
        const getCssObjectByRuleName = typeof cssObjectByRuleNameOrGetCssObjectByRuleName === 'function' ?
            cssObjectByRuleNameOrGetCssObjectByRuleName :
            () => cssObjectByRuleNameOrGetCssObjectByRuleName;
        function useStylesHook(params: Params) {
            const { cx, css, theme } = useStyles();
            let count = 0;
            function createRef() {
                return `tss-react-ref_${count++}`;
            }
            const cssObjectByRuleName = getCssObjectByRuleName(theme, params, createRef);
            const classes = Object.fromEntries(Object.keys(cssObjectByRuleName).map(ruleName => {
                const cssObject: CSSObject = cssObjectByRuleName[ruleName as RuleName];
                if (!cssObject.label) {
                    // Assign label to class name if none is provided
                    cssObject.label = labelPrefix + ruleName;
                }
                const className = css(cssObject);
                return [ruleName, className];
            })) as Record<RuleName, string>;
            return { classes, theme, css, cx, };
        }
        return useStylesHook;
    };
}
```

I think this would be a great addition to this library to make it easier to work with 👍

**Comment by garronej** [comment] 2021-10-12 13:17
Hi @olee,  
Seems like a nice addition!  
My concern is about maintainability.  
I want to make every effort possible to only push API that'll generate dry and maintainable code.  
With your proposal, if the component gets renamed we have to remember to update `makeStyle({ "name": ... })` as well.  
I would like to leverage [something like this](https://docs.tsafe.dev/main/symtostr).
It could let us write:  

```tsx
import { makeStyles } from "...";
import { symToStr } from "tsafe/symToStr";

const useStyles= makeStyles({ "name": symToString({ MyComponent }) })(
    theme=> ({})
);

function MyComponent(){
    //...
}
```

or even, if we use `symToStr` internally: 

```tsx
import { makeStyles } from "...";

const useStyles= makeStyles({ MyComponent })(
    theme=> ({})
);

function MyComponent(){
    //...
}
```

The problem is if we use react `memo`:  

```tsx
import { makeStyles } from "...";
import { memo } from "react";

const useStyles= makeStyles({ MyComponent })(
    theme=> ({})
);

const MyComponent = memo(()=>{
    //...
});
```

it will crash because `MyComponent` is declared after `makeStyles()` is invoked...  
idk if it's reasonable to expect users to move their styles under the component...  
After all why not? It's the costume in react native, we could then write something like:  

```tsx
import { makeStyles } from "...";
import { memo } from "react";

const MyComponent = memo(()=>{
    const { classes } = useStyles(); 
    //...
});  

const useStyles= makeStyles({ MyComponent })(
    theme=> ({})
);
```  

What are you though?

**Comment by garronej** [comment] 2021-10-12 22:15
>Usage with component function for name (not recommended imho!)
```tsx
function MyComponent(props) { 
  return <div {...props} />;
}
const useStyles = makeStyles({ name: MyComponent })({
  root: { /* ... */ },
});
```

We can't rely on `Function.prototype.name` because all react component should use `memo`. The component has to be wrapped.  

>  the counter which is used to generate starts from 0 on each useStyles invocation so the class names it generates are reused multiple times within the application.

It's not a bug. Those refs are for selecting children. It's like if you where saying you have multiple `x` variables declared across your application. Yes, but they are declared in different scopes so no need to explain why it's all good. 😉  


Regarding your proposal. It's not bat at all. I'll admit, I was a bit skeptical but your approach is quite clever.  
However, I would need you to work a little bit more on the types.  

I would need this to pass (or, per say, successfully fail):  

```tsx
import { assert } from "tsafe/assert";
import type { Equals } from "tsafe";

//@ts-expect-error: "xxx" should be added to the record of CSSObject
const useStyles = makeStyles({ "refs": [ "xxx" ] })(
	(theme, props, refs) => ({
		"root": {
			"backgroundColor": "red"
		}
	})
);

const { classes } = useStyles();

assert<Equals<typeof classes, Record<"root", "xxx", string>>();
```

Otherwise we could end up with error that goes unnoticed like:

```tsx
const useStyles = makeStyles({ "refs": [ "xxX" ] })(
	(theme, props, refs) => ({
                "xxx": {},
		"root": {
			[`& .${ref.xxX}`]: {
                             //This will never apply because "xxx" !== "xxX"
                        }
		}
	})
);
```

Also if a class key get rename maintainers will have to remember to rename also the refs.

 > which are not used that much yet anyway I guess?

Unfortunately, they are already widely used, it's a feature that have been requested.
I regret that we didn't go through this PR before I bumped to v1.0 but if it's really good I'll merge.

**Comment by olee** [comment] 2021-10-12 23:47
> Otherwise we could end up with error that goes unnoticed like:

That was exactly one of my concerns I noticed while continuing with the mui 5 upgrade in our project as well:
Renaming a class which was used as ref with implicit assignment could introduce errors which get unnoticed.
First I thought of it as a feature to allow users to give the ref a different name than the class, however I think this is actually not really useful and could just introduce bugs.

I will soon create a revised version with the required improvements.

As for the bug: [look here](https://codesandbox.io/s/tss-react-issues-26-40vpq?file=/src/index.tsx)
You will see that hovering `Root 1` will also trigger the style change for `Child 2` except it shouldn't.
If you however uncomment the `createRef()` in the second makeStyles to force it receiving a different name, it will work correctly.

**Comment by garronej** [comment] 2021-10-13 00:25
> As for the bug: [look here](https://codesandbox.io/s/tss-react-issues-26-40vpq?file=/src/index.tsx)

Yes indeed. This won't work but in my defence, [It is clearly stated](https://github.com/garronej/tss-react#selecting-children-by-class-name) that refs are to be used to select children.  
There is no parent selector in CSS so I just assumed that it would be a very uncommon pattern to do what you did in your example.  
That said, now that I see it, I think it makes sense to keep the styles dedicated for the child within the child.  
I deliberately didn't make the counter global because it would have a terrible impact on performance as the refs would gets constantly updated as component re-renders.  

This is an extra motivation for merging your proposal since it would work both ways but I don't want to settle on type safety and DRYness.

**Comment by garronej** [comment] 2021-10-13 02:20
> As for the bug: [look here](https://codesandbox.io/s/tss-react-issues-26-40vpq?file=/src/index.tsx)

Fixed in 1.0.3

**Comment by waynebloss** [comment] 2021-10-16 18:25
Is this similar to `classNamePrefix` [from JSS](https://cssinjs.org/jss-api/?v=v10.8.0#create-style-sheet)?

```js
import { makeStyles } from "@material-ui/core";

const useStyles = makeStyles(
  theme => ({
    root: { padding: 8 }
  }),
  { classNamePrefix: "ShowAppraisalPage" },
);
```

**Comment by garronej** [comment] 2021-10-19 18:28
Hi @olee,  
Do you still plan to make a PR for this?

**Comment by garronej** [comment] 2021-11-14 17:59
In `2.0.4`

**Closed by garronej** 2021-11-14 17:59 UTC
Labels: enhancement
